# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Guides & Resources
    url: guides/
    weight: 20
  - name: Diary
    url: blog/
    weight: 50
  - name: About
    url: about/
    weight: 60
  - name: Newsletter
    url: newsletter/
    weight: 70
  - name: Contact
    url: contact/
    weight: 80

sidebar:
  - identifier: more
    name: Looking for more foraging info?
    params:
      type: separator
    weight: 1
  - identifier: courses
    name: "Foraging Courses"
    pageRef: "/foraging-courses"
    weight: 2
  - identifier: downloads
    name: "Downloads"
    pageRef: "/downloads"
    weight: 4


