# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Plants
    url: docs/plants/
    weight: 20
  - name: Fungi
    url: docs/fungi/
    weight: 30
  - name: Resources
    url: docs/resources/
    weight: 40
  - name: Diary
    url: blog/
    weight: 50
  - name: About
    url: about/
    weight: 60

sidebar:
  - identifier: more
    name: Still need help?
    params:
      type: separator
    weight: 1
  - identifier: community
    name: "Community"
    pageRef: "/community"
    weight: 2
  - identifier: hugoDocs
    name: "Hugo Docs ↗"
    url: "https://docs.hugoblox.com"
    weight: 3
