# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: teal
  font: serif

# SEO
marketing:
  seo:
    site_type: Organisation
    local_business_type: 'ProfessionalService'
    org_name: 'The Foragers Diary'
    description: 'Wild food foraging guides, plant guides, mushroom and fungi guides, foraging resources and foraging courses'
    twitter: '@foragers_diary'
  analytics:
    google_analytics: 'G-VSR77TXTGQ'
    google_tag_manager: ''
    microsoft_clarity: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "logo.svg"
    button:
      enable: true
      text: "Newsletter"
      url: "/newsletter"
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  block: minimal
  copyright:
    notice: '© {year} The Foragers Diary.'
    license:
      enable: false
      allow_derivatives: false
      share_alike: false
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: ''
    content_dir: ''
    branch: ''
  feedback:
    responses:
      positive: ''
      negative: ''
  
  comment:
    provider: 'disqus'
    disqus:
      # Paste the shortname from your Disqus dashboard.
      shortname: 'foragersdiary'
      # Show comment count in page header? (true/false)
      show_count: true
